// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/auth/presentation/forget_password/bloc/forget_password_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flower_app/config/base_response/base_response.dart' as _i4;
import 'package:flower_app/core/ui_action/ui_action.dart' as _i11;
import 'package:flower_app/core/ui_action/ui_action_dispatcher.dart' as _i10;
import 'package:flower_app/features/auth/domain/entities/auth_message_entity.dart'
    as _i5;
import 'package:flower_app/features/auth/domain/entities/reset_token_entity.dart'
    as _i8;
import 'package:flower_app/features/auth/domain/use_cases/forget_password_use_case.dart'
    as _i2;
import 'package:flower_app/features/auth/domain/use_cases/reset_password_use_case.dart'
    as _i9;
import 'package:flower_app/features/auth/domain/use_cases/verify_otp_use_case.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [ForgetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordUseCase extends _i1.Mock
    implements _i2.ForgetPasswordUseCase {
  MockForgetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.AuthMessageEntity>> call({
    required String? email,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email}),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.AuthMessageEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.AuthMessageEntity>>(
                    this,
                    Invocation.method(#call, [], {#email: email}),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.AuthMessageEntity>>);
}

/// A class which mocks [VerifyOtpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyOtpUseCase extends _i1.Mock implements _i7.VerifyOtpUseCase {
  MockVerifyOtpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i8.ResetToken>> call({
    required String? email,
    required String? otpCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {#email: email, #otpCode: otpCode}),
            returnValue: _i3.Future<_i4.BaseResponse<_i8.ResetToken>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i8.ResetToken>>(
                this,
                Invocation.method(#call, [], {
                  #email: email,
                  #otpCode: otpCode,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i8.ResetToken>>);
}

/// A class which mocks [ResetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockResetPasswordUseCase extends _i1.Mock
    implements _i9.ResetPasswordUseCase {
  MockResetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.AuthMessageEntity>> call({
    required String? resetToken,
    required String? newPassword,
    required String? confirmNewPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #resetToken: resetToken,
              #newPassword: newPassword,
              #confirmNewPassword: confirmNewPassword,
            }),
            returnValue:
                _i3.Future<_i4.BaseResponse<_i5.AuthMessageEntity>>.value(
                  _i6.dummyValue<_i4.BaseResponse<_i5.AuthMessageEntity>>(
                    this,
                    Invocation.method(#call, [], {
                      #resetToken: resetToken,
                      #newPassword: newPassword,
                      #confirmNewPassword: confirmNewPassword,
                    }),
                  ),
                ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.AuthMessageEntity>>);
}

/// A class which mocks [UiActionDispatcher].
///
/// See the documentation for Mockito's code generation for more information.
class MockUiActionDispatcher extends _i1.Mock
    implements _i10.UiActionDispatcher {
  MockUiActionDispatcher() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i11.UiAction> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i3.Stream<_i11.UiAction>.empty(),
          )
          as _i3.Stream<_i11.UiAction>);

  @override
  void dispatch(_i11.UiAction? action) => super.noSuchMethod(
    Invocation.method(#dispatch, [action]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
