//
//
// import '../../data/models/city_area_model.dart';
//
// const List<CityAreaModel> cityAreaData = [
//   CityAreaModel(
//     city: 'Cairo',
//     areas: [
//       '15 May',
//       'Al Azbakeyah',
//       'Al Basatin',
//       'Tebin',
//       'El-Khalifa',
//       'El-Mokattam',
//       'Helwan',
//       'Dar Al Salam',
//       'Shubra',
//       'Tura',
//       'Abdeen',
//       'Abaseya',
//       'Ain Shams',
//       'Nasr City',
//       'New Heliopolis',
//       'Masr Al Qadima',
//       'Mansheya Nasir',
//       'Badr City',
//       'Obour City',
//       'Cairo Downtown',
//       'Zamalek',
//       'Kasr El Nile',
//       'Rehab',
//       'Katameya',
//       'Madinty',
//       'Rod Alfarag',
//       'Sheraton',
//       'El-Gamaleya',
//       '10th of Ramadan City',
//     ],
//   ),
//
//   CityAreaModel(
//     city: 'Giza',
//     areas: [
//       'Giza',
//       'Sixth of October',
//       'Cheikh Zayed',
//       'Hawamdiyah',
//       'Al Badrasheen',
//       'Saf',
//       'Atfih',
//       'Al Ayat',
//       'Al-Bawaiti',
//       'ManshiyetAl Qanater',
//       'Oaseem',
//       'Kerdasa',
//       'Abu Nomros',
//       'Kafr Ghati',
//       'Manshiyet Al Bakari',
//       'Dokki',
//       'Agouza',
//       'Haram',
//       'Warraq',
//     ],
//   ),
// ];