// Mocks generated by Mockito 5.4.6 from annotations
// in flower_app/test/features/auth/api/data_source_impl/auth_remote_data_source_imp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flower_app/features/auth/api/client/auth_api_client.dart'
    as _i4;
import 'package:flower_app/features/auth/data/models/login_request.dart' as _i6;
import 'package:flower_app/features/auth/data/models/login_response.dart'
    as _i2;
import 'package:flower_app/features/auth/data/models/register_request.dart'
    as _i7;
import 'package:flower_app/features/auth/data/models/register_response.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginResponse_0 extends _i1.SmartFake implements _i2.LoginResponse {
  _FakeLoginResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthResponse_1 extends _i1.SmartFake implements _i3.AuthResponse {
  _FakeAuthResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApiClient extends _i1.Mock implements _i4.AuthApiClient {
  MockAuthApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.LoginResponse> login(_i6.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i5.Future<_i2.LoginResponse>.value(
              _FakeLoginResponse_0(this, Invocation.method(#login, [request])),
            ),
          )
          as _i5.Future<_i2.LoginResponse>);

  @override
  _i5.Future<_i3.AuthResponse> register(
    _i7.SignUpRequest? request,
    String? language,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#register, [request, language]),
            returnValue: _i5.Future<_i3.AuthResponse>.value(
              _FakeAuthResponse_1(
                this,
                Invocation.method(#register, [request, language]),
              ),
            ),
          )
          as _i5.Future<_i3.AuthResponse>);
}
